on: push

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ucrt64
          update: true
          install: mingw-w64-ucrt-x86_64-toolchain base-devel cmake git zip msys2-runtime-devel
      - shell: msys2 {0}
        run: ./build.sh
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: build/uchardet.zip
      - uses: actions/upload-artifact@v4
        with:
          name: uchardet
          path: build/uchardet.zip
